/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'coach-profiles': CoachProfile;
    'subscriber-profiles': SubscriberProfile;
    categories: Category;
    tags: Tag;
    posts: Post;
    pages: Page;
    courses: Course;
    modules: Module;
    lessons: Lesson;
    quizzes: Quiz;
    enrollments: Enrollment;
    progress: Progress;
    'quiz-attempts': QuizAttempt;
    'contact-submissions': ContactSubmission;
    'newsletter-subscribers': NewsletterSubscriber;
    'coaching-sessions': CoachingSession;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'coach-profiles': CoachProfilesSelect<false> | CoachProfilesSelect<true>;
    'subscriber-profiles': SubscriberProfilesSelect<false> | SubscriberProfilesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    modules: ModulesSelect<false> | ModulesSelect<true>;
    lessons: LessonsSelect<false> | LessonsSelect<true>;
    quizzes: QuizzesSelect<false> | QuizzesSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    progress: ProgressSelect<false> | ProgressSelect<true>;
    'quiz-attempts': QuizAttemptsSelect<false> | QuizAttemptsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'coaching-sessions': CoachingSessionsSelect<false> | CoachingSessionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'blog-page': BlogPage;
    'courses-page': CoursesPage;
    'coaches-page': CoachesPage;
    'header-nav': HeaderNav;
    'footer-content': FooterContent;
    'meilisearch-admin': MeilisearchAdmin;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'courses-page': CoursesPageSelect<false> | CoursesPageSelect<true>;
    'coaches-page': CoachesPageSelect<false> | CoachesPageSelect<true>;
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    'footer-content': FooterContentSelect<false> | FooterContentSelect<true>;
    'meilisearch-admin': MeilisearchAdminSelect<false> | MeilisearchAdminSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * User accounts for authentication and authorization
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * User role determines permissions
   */
  role: 'subscriber' | 'creator' | 'coach' | 'admin';
  /**
   * Uncheck to block user login
   */
  isActive?: boolean | null;
  /**
   * Resend Contact ID for sync tracking
   */
  resendContactId?: string | null;
  isFirstLogin?: boolean | null;
  /**
   * User has opted out of marketing emails
   */
  unsubscribed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Unified media library with access control and signed URLs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility
   */
  alt: string;
  /**
   * Restrict this media to subscribers only.
   */
  isSubscriberOnly?: boolean | null;
  /**
   * Used for organizing media in storage
   */
  category: 'images' | 'videos' | 'documents';
  /**
   * User who uploaded this media
   */
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Public and professional coach information for content authoring and LMS
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-profiles".
 */
export interface CoachProfile {
  id: number;
  /**
   * The user account associated with this coach profile (one-to-one)
   */
  user?: (number | null) | User;
  /**
   * Public name shown on content and courses
   */
  displayName: string;
  /**
   * Will be automatically generated from display name if left empty.
   */
  slug?: string | null;
  /**
   * Public bio shown on profile and authored content
   */
  bio?: string | null;
  /**
   * Coach profile photo for public display
   */
  profilePhoto?: (number | null) | Media;
  /**
   * Areas of expertise and specialization
   */
  expertise?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Professional experience details
   */
  experience?: {
    yearsOfExperience?: number | null;
    /**
     * Certifications, qualifications, and credentials
     */
    credentials?: string | null;
    /**
     * Notable previous work or achievements
     */
    previousWork?: string | null;
  };
  /**
   * Whether this coach profile is currently active
   */
  isActive?: boolean | null;
  /**
   * Public social media and contact links
   */
  socialLinks?: {
    website?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  /**
   * Timezone for the availability slots below
   */
  timezone:
    | 'UTC'
    | 'Africa/Abidjan'
    | 'Africa/Accra'
    | 'Africa/Addis_Ababa'
    | 'Africa/Algiers'
    | 'Africa/Asmera'
    | 'Africa/Bamako'
    | 'Africa/Bangui'
    | 'Africa/Banjul'
    | 'Africa/Bissau'
    | 'Africa/Blantyre'
    | 'Africa/Brazzaville'
    | 'Africa/Bujumbura'
    | 'Africa/Cairo'
    | 'Africa/Casablanca'
    | 'Africa/Ceuta'
    | 'Africa/Conakry'
    | 'Africa/Dakar'
    | 'Africa/Dar_es_Salaam'
    | 'Africa/Djibouti'
    | 'Africa/Douala'
    | 'Africa/El_Aaiun'
    | 'Africa/Freetown'
    | 'Africa/Gaborone'
    | 'Africa/Harare'
    | 'Africa/Johannesburg'
    | 'Africa/Juba'
    | 'Africa/Kampala'
    | 'Africa/Khartoum'
    | 'Africa/Kigali'
    | 'Africa/Kinshasa'
    | 'Africa/Lagos'
    | 'Africa/Libreville'
    | 'Africa/Lome'
    | 'Africa/Luanda'
    | 'Africa/Lubumbashi'
    | 'Africa/Lusaka'
    | 'Africa/Malabo'
    | 'Africa/Maputo'
    | 'Africa/Maseru'
    | 'Africa/Mbabane'
    | 'Africa/Mogadishu'
    | 'Africa/Monrovia'
    | 'Africa/Nairobi'
    | 'Africa/Ndjamena'
    | 'Africa/Niamey'
    | 'Africa/Nouakchott'
    | 'Africa/Ouagadougou'
    | 'Africa/Porto-Novo'
    | 'Africa/Sao_Tome'
    | 'Africa/Tripoli'
    | 'Africa/Tunis'
    | 'Africa/Windhoek'
    | 'America/Adak'
    | 'America/Anchorage'
    | 'America/Anguilla'
    | 'America/Antigua'
    | 'America/Araguaina'
    | 'America/Argentina/La_Rioja'
    | 'America/Argentina/Rio_Gallegos'
    | 'America/Argentina/Salta'
    | 'America/Argentina/San_Juan'
    | 'America/Argentina/San_Luis'
    | 'America/Argentina/Tucuman'
    | 'America/Argentina/Ushuaia'
    | 'America/Aruba'
    | 'America/Asuncion'
    | 'America/Bahia'
    | 'America/Bahia_Banderas'
    | 'America/Barbados'
    | 'America/Belem'
    | 'America/Belize'
    | 'America/Blanc-Sablon'
    | 'America/Boa_Vista'
    | 'America/Bogota'
    | 'America/Boise'
    | 'America/Buenos_Aires'
    | 'America/Cambridge_Bay'
    | 'America/Campo_Grande'
    | 'America/Cancun'
    | 'America/Caracas'
    | 'America/Catamarca'
    | 'America/Cayenne'
    | 'America/Cayman'
    | 'America/Chicago'
    | 'America/Chihuahua'
    | 'America/Ciudad_Juarez'
    | 'America/Coral_Harbour'
    | 'America/Cordoba'
    | 'America/Costa_Rica'
    | 'America/Coyhaique'
    | 'America/Creston'
    | 'America/Cuiaba'
    | 'America/Curacao'
    | 'America/Danmarkshavn'
    | 'America/Dawson'
    | 'America/Dawson_Creek'
    | 'America/Denver'
    | 'America/Detroit'
    | 'America/Dominica'
    | 'America/Edmonton'
    | 'America/Eirunepe'
    | 'America/El_Salvador'
    | 'America/Fort_Nelson'
    | 'America/Fortaleza'
    | 'America/Glace_Bay'
    | 'America/Godthab'
    | 'America/Goose_Bay'
    | 'America/Grand_Turk'
    | 'America/Grenada'
    | 'America/Guadeloupe'
    | 'America/Guatemala'
    | 'America/Guayaquil'
    | 'America/Guyana'
    | 'America/Halifax'
    | 'America/Havana'
    | 'America/Hermosillo'
    | 'America/Indiana/Knox'
    | 'America/Indiana/Marengo'
    | 'America/Indiana/Petersburg'
    | 'America/Indiana/Tell_City'
    | 'America/Indiana/Vevay'
    | 'America/Indiana/Vincennes'
    | 'America/Indiana/Winamac'
    | 'America/Indianapolis'
    | 'America/Inuvik'
    | 'America/Iqaluit'
    | 'America/Jamaica'
    | 'America/Jujuy'
    | 'America/Juneau'
    | 'America/Kentucky/Monticello'
    | 'America/Kralendijk'
    | 'America/La_Paz'
    | 'America/Lima'
    | 'America/Los_Angeles'
    | 'America/Louisville'
    | 'America/Lower_Princes'
    | 'America/Maceio'
    | 'America/Managua'
    | 'America/Manaus'
    | 'America/Marigot'
    | 'America/Martinique'
    | 'America/Matamoros'
    | 'America/Mazatlan'
    | 'America/Mendoza'
    | 'America/Menominee'
    | 'America/Merida'
    | 'America/Metlakatla'
    | 'America/Mexico_City'
    | 'America/Miquelon'
    | 'America/Moncton'
    | 'America/Monterrey'
    | 'America/Montevideo'
    | 'America/Montserrat'
    | 'America/Nassau'
    | 'America/New_York'
    | 'America/Nome'
    | 'America/Noronha'
    | 'America/North_Dakota/Beulah'
    | 'America/North_Dakota/Center'
    | 'America/North_Dakota/New_Salem'
    | 'America/Ojinaga'
    | 'America/Panama'
    | 'America/Paramaribo'
    | 'America/Phoenix'
    | 'America/Port-au-Prince'
    | 'America/Port_of_Spain'
    | 'America/Porto_Velho'
    | 'America/Puerto_Rico'
    | 'America/Punta_Arenas'
    | 'America/Rankin_Inlet'
    | 'America/Recife'
    | 'America/Regina'
    | 'America/Resolute'
    | 'America/Rio_Branco'
    | 'America/Santarem'
    | 'America/Santiago'
    | 'America/Santo_Domingo'
    | 'America/Sao_Paulo'
    | 'America/Scoresbysund'
    | 'America/Sitka'
    | 'America/St_Barthelemy'
    | 'America/St_Johns'
    | 'America/St_Kitts'
    | 'America/St_Lucia'
    | 'America/St_Thomas'
    | 'America/St_Vincent'
    | 'America/Swift_Current'
    | 'America/Tegucigalpa'
    | 'America/Thule'
    | 'America/Tijuana'
    | 'America/Toronto'
    | 'America/Tortola'
    | 'America/Vancouver'
    | 'America/Whitehorse'
    | 'America/Winnipeg'
    | 'America/Yakutat'
    | 'Antarctica/Casey'
    | 'Antarctica/Davis'
    | 'Antarctica/DumontDUrville'
    | 'Antarctica/Macquarie'
    | 'Antarctica/Mawson'
    | 'Antarctica/McMurdo'
    | 'Antarctica/Palmer'
    | 'Antarctica/Rothera'
    | 'Antarctica/Syowa'
    | 'Antarctica/Troll'
    | 'Antarctica/Vostok'
    | 'Arctic/Longyearbyen'
    | 'Asia/Aden'
    | 'Asia/Almaty'
    | 'Asia/Amman'
    | 'Asia/Anadyr'
    | 'Asia/Aqtau'
    | 'Asia/Aqtobe'
    | 'Asia/Ashgabat'
    | 'Asia/Atyrau'
    | 'Asia/Baghdad'
    | 'Asia/Bahrain'
    | 'Asia/Baku'
    | 'Asia/Bangkok'
    | 'Asia/Barnaul'
    | 'Asia/Beirut'
    | 'Asia/Bishkek'
    | 'Asia/Brunei'
    | 'Asia/Calcutta'
    | 'Asia/Chita'
    | 'Asia/Colombo'
    | 'Asia/Damascus'
    | 'Asia/Dhaka'
    | 'Asia/Dili'
    | 'Asia/Dubai'
    | 'Asia/Dushanbe'
    | 'Asia/Famagusta'
    | 'Asia/Gaza'
    | 'Asia/Hebron'
    | 'Asia/Hong_Kong'
    | 'Asia/Hovd'
    | 'Asia/Irkutsk'
    | 'Asia/Jakarta'
    | 'Asia/Jayapura'
    | 'Asia/Jerusalem'
    | 'Asia/Kabul'
    | 'Asia/Kamchatka'
    | 'Asia/Karachi'
    | 'Asia/Katmandu'
    | 'Asia/Khandyga'
    | 'Asia/Krasnoyarsk'
    | 'Asia/Kuala_Lumpur'
    | 'Asia/Kuching'
    | 'Asia/Kuwait'
    | 'Asia/Macau'
    | 'Asia/Magadan'
    | 'Asia/Makassar'
    | 'Asia/Manila'
    | 'Asia/Muscat'
    | 'Asia/Nicosia'
    | 'Asia/Novokuznetsk'
    | 'Asia/Novosibirsk'
    | 'Asia/Omsk'
    | 'Asia/Oral'
    | 'Asia/Phnom_Penh'
    | 'Asia/Pontianak'
    | 'Asia/Pyongyang'
    | 'Asia/Qatar'
    | 'Asia/Qostanay'
    | 'Asia/Qyzylorda'
    | 'Asia/Rangoon'
    | 'Asia/Riyadh'
    | 'Asia/Saigon'
    | 'Asia/Sakhalin'
    | 'Asia/Samarkand'
    | 'Asia/Seoul'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Srednekolymsk'
    | 'Asia/Taipei'
    | 'Asia/Tashkent'
    | 'Asia/Tbilisi'
    | 'Asia/Tehran'
    | 'Asia/Thimphu'
    | 'Asia/Tokyo'
    | 'Asia/Tomsk'
    | 'Asia/Ulaanbaatar'
    | 'Asia/Urumqi'
    | 'Asia/Ust-Nera'
    | 'Asia/Vientiane'
    | 'Asia/Vladivostok'
    | 'Asia/Yakutsk'
    | 'Asia/Yekaterinburg'
    | 'Asia/Yerevan'
    | 'Atlantic/Azores'
    | 'Atlantic/Bermuda'
    | 'Atlantic/Canary'
    | 'Atlantic/Cape_Verde'
    | 'Atlantic/Faeroe'
    | 'Atlantic/Madeira'
    | 'Atlantic/Reykjavik'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/St_Helena'
    | 'Atlantic/Stanley'
    | 'Australia/Adelaide'
    | 'Australia/Brisbane'
    | 'Australia/Broken_Hill'
    | 'Australia/Darwin'
    | 'Australia/Eucla'
    | 'Australia/Hobart'
    | 'Australia/Lindeman'
    | 'Australia/Lord_Howe'
    | 'Australia/Melbourne'
    | 'Australia/Perth'
    | 'Australia/Sydney'
    | 'Europe/Amsterdam'
    | 'Europe/Andorra'
    | 'Europe/Astrakhan'
    | 'Europe/Athens'
    | 'Europe/Belgrade'
    | 'Europe/Berlin'
    | 'Europe/Bratislava'
    | 'Europe/Brussels'
    | 'Europe/Bucharest'
    | 'Europe/Budapest'
    | 'Europe/Busingen'
    | 'Europe/Chisinau'
    | 'Europe/Copenhagen'
    | 'Europe/Dublin'
    | 'Europe/Gibraltar'
    | 'Europe/Guernsey'
    | 'Europe/Helsinki'
    | 'Europe/Isle_of_Man'
    | 'Europe/Istanbul'
    | 'Europe/Jersey'
    | 'Europe/Kaliningrad'
    | 'Europe/Kiev'
    | 'Europe/Kirov'
    | 'Europe/Lisbon'
    | 'Europe/Ljubljana'
    | 'Europe/London'
    | 'Europe/Luxembourg'
    | 'Europe/Madrid'
    | 'Europe/Malta'
    | 'Europe/Mariehamn'
    | 'Europe/Minsk'
    | 'Europe/Monaco'
    | 'Europe/Moscow'
    | 'Europe/Oslo'
    | 'Europe/Paris'
    | 'Europe/Podgorica'
    | 'Europe/Prague'
    | 'Europe/Riga'
    | 'Europe/Rome'
    | 'Europe/Samara'
    | 'Europe/San_Marino'
    | 'Europe/Sarajevo'
    | 'Europe/Saratov'
    | 'Europe/Simferopol'
    | 'Europe/Skopje'
    | 'Europe/Sofia'
    | 'Europe/Stockholm'
    | 'Europe/Tallinn'
    | 'Europe/Tirane'
    | 'Europe/Ulyanovsk'
    | 'Europe/Vaduz'
    | 'Europe/Vatican'
    | 'Europe/Vienna'
    | 'Europe/Vilnius'
    | 'Europe/Volgograd'
    | 'Europe/Warsaw'
    | 'Europe/Zagreb'
    | 'Europe/Zurich'
    | 'Indian/Antananarivo'
    | 'Indian/Chagos'
    | 'Indian/Christmas'
    | 'Indian/Cocos'
    | 'Indian/Comoro'
    | 'Indian/Kerguelen'
    | 'Indian/Mahe'
    | 'Indian/Maldives'
    | 'Indian/Mauritius'
    | 'Indian/Mayotte'
    | 'Indian/Reunion'
    | 'Pacific/Apia'
    | 'Pacific/Auckland'
    | 'Pacific/Bougainville'
    | 'Pacific/Chatham'
    | 'Pacific/Easter'
    | 'Pacific/Efate'
    | 'Pacific/Enderbury'
    | 'Pacific/Fakaofo'
    | 'Pacific/Fiji'
    | 'Pacific/Funafuti'
    | 'Pacific/Galapagos'
    | 'Pacific/Gambier'
    | 'Pacific/Guadalcanal'
    | 'Pacific/Guam'
    | 'Pacific/Honolulu'
    | 'Pacific/Kiritimati'
    | 'Pacific/Kosrae'
    | 'Pacific/Kwajalein'
    | 'Pacific/Majuro'
    | 'Pacific/Marquesas'
    | 'Pacific/Midway'
    | 'Pacific/Nauru'
    | 'Pacific/Niue'
    | 'Pacific/Norfolk'
    | 'Pacific/Noumea'
    | 'Pacific/Pago_Pago'
    | 'Pacific/Palau'
    | 'Pacific/Pitcairn'
    | 'Pacific/Ponape'
    | 'Pacific/Port_Moresby'
    | 'Pacific/Rarotonga'
    | 'Pacific/Saipan'
    | 'Pacific/Tahiti'
    | 'Pacific/Tarawa'
    | 'Pacific/Tongatapu'
    | 'Pacific/Truk'
    | 'Pacific/Wake'
    | 'Pacific/Wallis';
  /**
   * Define recurring weekly availability slots.
   */
  availability?:
    | {
        day: 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Learner-specific profile information for subscribers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-profiles".
 */
export interface SubscriberProfile {
  id: number;
  /**
   * The user account associated with this subscriber profile (one-to-one)
   */
  user: number | User;
  /**
   * Display name shown in comments, forums, and community features
   */
  displayName: string;
  /**
   * Subscriber avatar for community features
   */
  avatar?: (number | null) | Media;
  /**
   * If enabled, this subscriber prefers anonymous participation
   */
  isAnonymous?: boolean | null;
  /**
   * Topics and subjects the subscriber is interested in
   */
  interests?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional subscriber metadata
   */
  metadata?: {
    /**
     * Preferred timezone for scheduling and notifications
     */
    timezone?:
      | (
          | 'UTC'
          | 'Africa/Abidjan'
          | 'Africa/Accra'
          | 'Africa/Addis_Ababa'
          | 'Africa/Algiers'
          | 'Africa/Asmera'
          | 'Africa/Bamako'
          | 'Africa/Bangui'
          | 'Africa/Banjul'
          | 'Africa/Bissau'
          | 'Africa/Blantyre'
          | 'Africa/Brazzaville'
          | 'Africa/Bujumbura'
          | 'Africa/Cairo'
          | 'Africa/Casablanca'
          | 'Africa/Ceuta'
          | 'Africa/Conakry'
          | 'Africa/Dakar'
          | 'Africa/Dar_es_Salaam'
          | 'Africa/Djibouti'
          | 'Africa/Douala'
          | 'Africa/El_Aaiun'
          | 'Africa/Freetown'
          | 'Africa/Gaborone'
          | 'Africa/Harare'
          | 'Africa/Johannesburg'
          | 'Africa/Juba'
          | 'Africa/Kampala'
          | 'Africa/Khartoum'
          | 'Africa/Kigali'
          | 'Africa/Kinshasa'
          | 'Africa/Lagos'
          | 'Africa/Libreville'
          | 'Africa/Lome'
          | 'Africa/Luanda'
          | 'Africa/Lubumbashi'
          | 'Africa/Lusaka'
          | 'Africa/Malabo'
          | 'Africa/Maputo'
          | 'Africa/Maseru'
          | 'Africa/Mbabane'
          | 'Africa/Mogadishu'
          | 'Africa/Monrovia'
          | 'Africa/Nairobi'
          | 'Africa/Ndjamena'
          | 'Africa/Niamey'
          | 'Africa/Nouakchott'
          | 'Africa/Ouagadougou'
          | 'Africa/Porto-Novo'
          | 'Africa/Sao_Tome'
          | 'Africa/Tripoli'
          | 'Africa/Tunis'
          | 'Africa/Windhoek'
          | 'America/Adak'
          | 'America/Anchorage'
          | 'America/Anguilla'
          | 'America/Antigua'
          | 'America/Araguaina'
          | 'America/Argentina/La_Rioja'
          | 'America/Argentina/Rio_Gallegos'
          | 'America/Argentina/Salta'
          | 'America/Argentina/San_Juan'
          | 'America/Argentina/San_Luis'
          | 'America/Argentina/Tucuman'
          | 'America/Argentina/Ushuaia'
          | 'America/Aruba'
          | 'America/Asuncion'
          | 'America/Bahia'
          | 'America/Bahia_Banderas'
          | 'America/Barbados'
          | 'America/Belem'
          | 'America/Belize'
          | 'America/Blanc-Sablon'
          | 'America/Boa_Vista'
          | 'America/Bogota'
          | 'America/Boise'
          | 'America/Buenos_Aires'
          | 'America/Cambridge_Bay'
          | 'America/Campo_Grande'
          | 'America/Cancun'
          | 'America/Caracas'
          | 'America/Catamarca'
          | 'America/Cayenne'
          | 'America/Cayman'
          | 'America/Chicago'
          | 'America/Chihuahua'
          | 'America/Ciudad_Juarez'
          | 'America/Coral_Harbour'
          | 'America/Cordoba'
          | 'America/Costa_Rica'
          | 'America/Coyhaique'
          | 'America/Creston'
          | 'America/Cuiaba'
          | 'America/Curacao'
          | 'America/Danmarkshavn'
          | 'America/Dawson'
          | 'America/Dawson_Creek'
          | 'America/Denver'
          | 'America/Detroit'
          | 'America/Dominica'
          | 'America/Edmonton'
          | 'America/Eirunepe'
          | 'America/El_Salvador'
          | 'America/Fort_Nelson'
          | 'America/Fortaleza'
          | 'America/Glace_Bay'
          | 'America/Godthab'
          | 'America/Goose_Bay'
          | 'America/Grand_Turk'
          | 'America/Grenada'
          | 'America/Guadeloupe'
          | 'America/Guatemala'
          | 'America/Guayaquil'
          | 'America/Guyana'
          | 'America/Halifax'
          | 'America/Havana'
          | 'America/Hermosillo'
          | 'America/Indiana/Knox'
          | 'America/Indiana/Marengo'
          | 'America/Indiana/Petersburg'
          | 'America/Indiana/Tell_City'
          | 'America/Indiana/Vevay'
          | 'America/Indiana/Vincennes'
          | 'America/Indiana/Winamac'
          | 'America/Indianapolis'
          | 'America/Inuvik'
          | 'America/Iqaluit'
          | 'America/Jamaica'
          | 'America/Jujuy'
          | 'America/Juneau'
          | 'America/Kentucky/Monticello'
          | 'America/Kralendijk'
          | 'America/La_Paz'
          | 'America/Lima'
          | 'America/Los_Angeles'
          | 'America/Louisville'
          | 'America/Lower_Princes'
          | 'America/Maceio'
          | 'America/Managua'
          | 'America/Manaus'
          | 'America/Marigot'
          | 'America/Martinique'
          | 'America/Matamoros'
          | 'America/Mazatlan'
          | 'America/Mendoza'
          | 'America/Menominee'
          | 'America/Merida'
          | 'America/Metlakatla'
          | 'America/Mexico_City'
          | 'America/Miquelon'
          | 'America/Moncton'
          | 'America/Monterrey'
          | 'America/Montevideo'
          | 'America/Montserrat'
          | 'America/Nassau'
          | 'America/New_York'
          | 'America/Nome'
          | 'America/Noronha'
          | 'America/North_Dakota/Beulah'
          | 'America/North_Dakota/Center'
          | 'America/North_Dakota/New_Salem'
          | 'America/Ojinaga'
          | 'America/Panama'
          | 'America/Paramaribo'
          | 'America/Phoenix'
          | 'America/Port-au-Prince'
          | 'America/Port_of_Spain'
          | 'America/Porto_Velho'
          | 'America/Puerto_Rico'
          | 'America/Punta_Arenas'
          | 'America/Rankin_Inlet'
          | 'America/Recife'
          | 'America/Regina'
          | 'America/Resolute'
          | 'America/Rio_Branco'
          | 'America/Santarem'
          | 'America/Santiago'
          | 'America/Santo_Domingo'
          | 'America/Sao_Paulo'
          | 'America/Scoresbysund'
          | 'America/Sitka'
          | 'America/St_Barthelemy'
          | 'America/St_Johns'
          | 'America/St_Kitts'
          | 'America/St_Lucia'
          | 'America/St_Thomas'
          | 'America/St_Vincent'
          | 'America/Swift_Current'
          | 'America/Tegucigalpa'
          | 'America/Thule'
          | 'America/Tijuana'
          | 'America/Toronto'
          | 'America/Tortola'
          | 'America/Vancouver'
          | 'America/Whitehorse'
          | 'America/Winnipeg'
          | 'America/Yakutat'
          | 'Antarctica/Casey'
          | 'Antarctica/Davis'
          | 'Antarctica/DumontDUrville'
          | 'Antarctica/Macquarie'
          | 'Antarctica/Mawson'
          | 'Antarctica/McMurdo'
          | 'Antarctica/Palmer'
          | 'Antarctica/Rothera'
          | 'Antarctica/Syowa'
          | 'Antarctica/Troll'
          | 'Antarctica/Vostok'
          | 'Arctic/Longyearbyen'
          | 'Asia/Aden'
          | 'Asia/Almaty'
          | 'Asia/Amman'
          | 'Asia/Anadyr'
          | 'Asia/Aqtau'
          | 'Asia/Aqtobe'
          | 'Asia/Ashgabat'
          | 'Asia/Atyrau'
          | 'Asia/Baghdad'
          | 'Asia/Bahrain'
          | 'Asia/Baku'
          | 'Asia/Bangkok'
          | 'Asia/Barnaul'
          | 'Asia/Beirut'
          | 'Asia/Bishkek'
          | 'Asia/Brunei'
          | 'Asia/Calcutta'
          | 'Asia/Chita'
          | 'Asia/Colombo'
          | 'Asia/Damascus'
          | 'Asia/Dhaka'
          | 'Asia/Dili'
          | 'Asia/Dubai'
          | 'Asia/Dushanbe'
          | 'Asia/Famagusta'
          | 'Asia/Gaza'
          | 'Asia/Hebron'
          | 'Asia/Hong_Kong'
          | 'Asia/Hovd'
          | 'Asia/Irkutsk'
          | 'Asia/Jakarta'
          | 'Asia/Jayapura'
          | 'Asia/Jerusalem'
          | 'Asia/Kabul'
          | 'Asia/Kamchatka'
          | 'Asia/Karachi'
          | 'Asia/Katmandu'
          | 'Asia/Khandyga'
          | 'Asia/Krasnoyarsk'
          | 'Asia/Kuala_Lumpur'
          | 'Asia/Kuching'
          | 'Asia/Kuwait'
          | 'Asia/Macau'
          | 'Asia/Magadan'
          | 'Asia/Makassar'
          | 'Asia/Manila'
          | 'Asia/Muscat'
          | 'Asia/Nicosia'
          | 'Asia/Novokuznetsk'
          | 'Asia/Novosibirsk'
          | 'Asia/Omsk'
          | 'Asia/Oral'
          | 'Asia/Phnom_Penh'
          | 'Asia/Pontianak'
          | 'Asia/Pyongyang'
          | 'Asia/Qatar'
          | 'Asia/Qostanay'
          | 'Asia/Qyzylorda'
          | 'Asia/Rangoon'
          | 'Asia/Riyadh'
          | 'Asia/Saigon'
          | 'Asia/Sakhalin'
          | 'Asia/Samarkand'
          | 'Asia/Seoul'
          | 'Asia/Shanghai'
          | 'Asia/Singapore'
          | 'Asia/Srednekolymsk'
          | 'Asia/Taipei'
          | 'Asia/Tashkent'
          | 'Asia/Tbilisi'
          | 'Asia/Tehran'
          | 'Asia/Thimphu'
          | 'Asia/Tokyo'
          | 'Asia/Tomsk'
          | 'Asia/Ulaanbaatar'
          | 'Asia/Urumqi'
          | 'Asia/Ust-Nera'
          | 'Asia/Vientiane'
          | 'Asia/Vladivostok'
          | 'Asia/Yakutsk'
          | 'Asia/Yekaterinburg'
          | 'Asia/Yerevan'
          | 'Atlantic/Azores'
          | 'Atlantic/Bermuda'
          | 'Atlantic/Canary'
          | 'Atlantic/Cape_Verde'
          | 'Atlantic/Faeroe'
          | 'Atlantic/Madeira'
          | 'Atlantic/Reykjavik'
          | 'Atlantic/South_Georgia'
          | 'Atlantic/St_Helena'
          | 'Atlantic/Stanley'
          | 'Australia/Adelaide'
          | 'Australia/Brisbane'
          | 'Australia/Broken_Hill'
          | 'Australia/Darwin'
          | 'Australia/Eucla'
          | 'Australia/Hobart'
          | 'Australia/Lindeman'
          | 'Australia/Lord_Howe'
          | 'Australia/Melbourne'
          | 'Australia/Perth'
          | 'Australia/Sydney'
          | 'Europe/Amsterdam'
          | 'Europe/Andorra'
          | 'Europe/Astrakhan'
          | 'Europe/Athens'
          | 'Europe/Belgrade'
          | 'Europe/Berlin'
          | 'Europe/Bratislava'
          | 'Europe/Brussels'
          | 'Europe/Bucharest'
          | 'Europe/Budapest'
          | 'Europe/Busingen'
          | 'Europe/Chisinau'
          | 'Europe/Copenhagen'
          | 'Europe/Dublin'
          | 'Europe/Gibraltar'
          | 'Europe/Guernsey'
          | 'Europe/Helsinki'
          | 'Europe/Isle_of_Man'
          | 'Europe/Istanbul'
          | 'Europe/Jersey'
          | 'Europe/Kaliningrad'
          | 'Europe/Kiev'
          | 'Europe/Kirov'
          | 'Europe/Lisbon'
          | 'Europe/Ljubljana'
          | 'Europe/London'
          | 'Europe/Luxembourg'
          | 'Europe/Madrid'
          | 'Europe/Malta'
          | 'Europe/Mariehamn'
          | 'Europe/Minsk'
          | 'Europe/Monaco'
          | 'Europe/Moscow'
          | 'Europe/Oslo'
          | 'Europe/Paris'
          | 'Europe/Podgorica'
          | 'Europe/Prague'
          | 'Europe/Riga'
          | 'Europe/Rome'
          | 'Europe/Samara'
          | 'Europe/San_Marino'
          | 'Europe/Sarajevo'
          | 'Europe/Saratov'
          | 'Europe/Simferopol'
          | 'Europe/Skopje'
          | 'Europe/Sofia'
          | 'Europe/Stockholm'
          | 'Europe/Tallinn'
          | 'Europe/Tirane'
          | 'Europe/Ulyanovsk'
          | 'Europe/Vaduz'
          | 'Europe/Vatican'
          | 'Europe/Vienna'
          | 'Europe/Vilnius'
          | 'Europe/Volgograd'
          | 'Europe/Warsaw'
          | 'Europe/Zagreb'
          | 'Europe/Zurich'
          | 'Indian/Antananarivo'
          | 'Indian/Chagos'
          | 'Indian/Christmas'
          | 'Indian/Cocos'
          | 'Indian/Comoro'
          | 'Indian/Kerguelen'
          | 'Indian/Mahe'
          | 'Indian/Maldives'
          | 'Indian/Mauritius'
          | 'Indian/Mayotte'
          | 'Indian/Reunion'
          | 'Pacific/Apia'
          | 'Pacific/Auckland'
          | 'Pacific/Bougainville'
          | 'Pacific/Chatham'
          | 'Pacific/Easter'
          | 'Pacific/Efate'
          | 'Pacific/Enderbury'
          | 'Pacific/Fakaofo'
          | 'Pacific/Fiji'
          | 'Pacific/Funafuti'
          | 'Pacific/Galapagos'
          | 'Pacific/Gambier'
          | 'Pacific/Guadalcanal'
          | 'Pacific/Guam'
          | 'Pacific/Honolulu'
          | 'Pacific/Kiritimati'
          | 'Pacific/Kosrae'
          | 'Pacific/Kwajalein'
          | 'Pacific/Majuro'
          | 'Pacific/Marquesas'
          | 'Pacific/Midway'
          | 'Pacific/Nauru'
          | 'Pacific/Niue'
          | 'Pacific/Norfolk'
          | 'Pacific/Noumea'
          | 'Pacific/Pago_Pago'
          | 'Pacific/Palau'
          | 'Pacific/Pitcairn'
          | 'Pacific/Ponape'
          | 'Pacific/Port_Moresby'
          | 'Pacific/Rarotonga'
          | 'Pacific/Saipan'
          | 'Pacific/Tahiti'
          | 'Pacific/Tarawa'
          | 'Pacific/Tongatapu'
          | 'Pacific/Truk'
          | 'Pacific/Wake'
          | 'Pacific/Wallis'
        )
      | null;
    /**
     * Preferred language code
     */
    language?: string | null;
    /**
     * Date when subscriber profile was created
     */
    joinedAt?: string | null;
  };
  /**
   * Learning style and delivery preferences
   */
  learningPreferences?: {
    preferredFormat?: ('video' | 'text' | 'audio') | null;
    pace?: ('self-paced' | 'scheduled' | 'intensive') | null;
  };
  /**
   * Whether this subscriber profile is currently active
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Content categories for blogs and articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  description?: string | null;
  /**
   * Whether this category is active and visible
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tags for content classification and discovery
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Will be automatically generated from name if left empty.
   */
  slug?: string | null;
  /**
   * Whether this tag is active and visible
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts and articles
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  /**
   * The coach who authored this post
   */
  author: number | CoachProfile;
  /**
   * Featured image for the post
   */
  featuredImage?: (number | null) | Media;
  /**
   * Short summary shown in post listings
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  /**
   * Restrict this post to subscribers only
   */
  isSubscriberOnly?: boolean | null;
  /**
   * Publication date for the post
   */
  publishedAt?: string | null;
  /**
   * Whether this post is visible to the public (or subscribers if set)
   */
  isPublished?: boolean | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title for search engines (defaults to post title)
     */
    metaTitle?: string | null;
    /**
     * Description for search engines
     */
    metaDescription?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Static pages for the website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  /**
   * The coach or admin who authored/maintains this page
   */
  author?:
    | ({
        relationTo: 'coach-profiles';
        value: number | CoachProfile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Whether this page is visible to the public
   */
  isPublished?: boolean | null;
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title for search engines (defaults to page title)
     */
    metaTitle?: string | null;
    /**
     * Description for search engines
     */
    metaDescription?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Online courses and learning programs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Course title displayed to learners
   */
  title: string;
  /**
   * Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  /**
   * Detailed course description and overview
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Brief summary for course listings and cards
   */
  shortDescription?: string | null;
  /**
   * Primary instructor for this course
   */
  instructor: number | CoachProfile;
  /**
   * Co-instructors or guest lecturers
   */
  additionalInstructors?: (number | CoachProfile)[] | null;
  /**
   * Course thumbnail image for listings
   */
  thumbnail?: (number | null) | Media;
  /**
   * Large cover image for course landing page
   */
  coverImage?: (number | null) | Media;
  /**
   * URL to preview/intro video (YouTube, Vimeo, etc.)
   */
  previewVideo?: string | null;
  /**
   * Ordered list of modules in this course
   */
  modules?: (number | Module)[] | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced' | 'all-levels') | null;
  /**
   * Estimated course duration
   */
  duration?: {
    hours?: number | null;
    minutes?: number | null;
  };
  /**
   * Key topics covered in this course
   */
  topics?:
    | {
        topic: string;
        id?: string | null;
      }[]
    | null;
  /**
   * What learners will achieve after completing the course
   */
  learningOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Required knowledge or courses before starting
   */
  prerequisites?:
    | {
        prerequisite: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enrollment configuration
   */
  enrollment?: {
    /**
     * Whether new enrollments are accepted
     */
    isOpen?: boolean | null;
    /**
     * Maximum number of enrollments (0 = unlimited)
     */
    maxEnrollments?: number | null;
    /**
     * When the course becomes available
     */
    startDate?: string | null;
    /**
     * When the course closes (optional)
     */
    endDate?: string | null;
  };
  /**
   * Whether this course is visible to learners
   */
  isPublished?: boolean | null;
  /**
   * Publication date
   */
  publishedAt?: string | null;
  /**
   * Primary course category
   */
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  /**
   * Search engine optimization
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Open Graph image for social sharing
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Course modules - organized sections within a course
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules".
 */
export interface Module {
  id: number;
  /**
   * Module title
   */
  title: string;
  /**
   * Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  /**
   * Brief description of what this module covers
   */
  description?: string | null;
  /**
   * Display order within the course (lower = earlier)
   */
  order: number;
  /**
   * Ordered list of lessons in this module
   */
  lessons?: (number | Lesson)[] | null;
  /**
   * Requirements to mark this module as complete
   */
  completionRequirements?: {
    /**
     * Must complete all lessons to finish module
     */
    requireAllLessons?: boolean | null;
    /**
     * Minimum number of lessons to complete (if not all required)
     */
    minimumLessons?: number | null;
    /**
     * Must pass module quiz to complete
     */
    requireQuizPass?: boolean | null;
  };
  /**
   * Estimated time to complete this module
   */
  estimatedDuration?: {
    hours?: number | null;
    minutes?: number | null;
  };
  /**
   * Learning objectives for this module
   */
  objectives?:
    | {
        objective: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional quiz to assess module understanding
   */
  quiz?: (number | null) | Quiz;
  /**
   * Whether this module is visible to learners
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual lessons with learning content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons".
 */
export interface Lesson {
  id: number;
  /**
   * Lesson title
   */
  title: string;
  /**
   * Will be automatically generated from title if left empty.
   */
  slug?: string | null;
  /**
   * Brief description of the lesson
   */
  description?: string | null;
  /**
   * Display order within the module (lower = earlier)
   */
  order: number;
  /**
   * Primary content type for this lesson
   */
  type: 'video' | 'text' | 'audio' | 'quiz';
  /**
   * Video lesson content
   */
  videoContent?: {
    /**
     * External video URL (YouTube, Vimeo, etc.)
     */
    videoUrl?: string | null;
    /**
     * Uploaded video file
     */
    videoFile?: (number | null) | Media;
    /**
     * Video transcript for accessibility
     */
    transcript?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Captions/subtitles file (VTT format)
     */
    captions?: (number | null) | Media;
  };
  /**
   * Text-based lesson content
   */
  textContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Audio lesson content
   */
  audioContent?: {
    audioFile?: (number | null) | Media;
    /**
     * Audio transcript for accessibility
     */
    transcript?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Associated quiz for this lesson
   */
  quiz?: (number | null) | Quiz;
  /**
   * Downloadable resources and materials
   */
  resources?:
    | {
        title: string;
        file: number | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Estimated time to complete
   */
  duration?: {
    hours?: number | null;
    minutes?: number | null;
  };
  /**
   * Make this lesson available as a free preview
   */
  isFree?: boolean | null;
  /**
   * How is this lesson marked as complete
   */
  completionCriteria?: ('view' | 'video-complete' | 'quiz-pass' | 'manual') | null;
  /**
   * Whether this lesson is visible to learners
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quizzes and assessments for lessons and modules
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes".
 */
export interface Quiz {
  id: number;
  /**
   * Quiz title
   */
  title: string;
  /**
   * Instructions or description for the quiz
   */
  description?: string | null;
  /**
   * Quiz configuration
   */
  settings?: {
    /**
     * Time limit in minutes (0 = no limit)
     */
    timeLimit?: number | null;
    /**
     * Minimum percentage to pass
     */
    passingScore?: number | null;
    /**
     * Maximum attempts allowed (0 = unlimited)
     */
    maxAttempts?: number | null;
    /**
     * Randomize question order for each attempt
     */
    shuffleQuestions?: boolean | null;
    /**
     * When to show correct answers
     */
    showCorrectAnswers?: ('never' | 'after-submit' | 'after-pass' | 'after-attempts') | null;
    /**
     * Allow learners to review their answers
     */
    allowReview?: boolean | null;
  };
  /**
   * Quiz questions (contains answers - only visible to coaches/admins)
   */
  questions: {
    questionType: 'multiple-choice' | 'multiple-select' | 'true-false' | 'short-answer' | 'essay' | 'fill-blank';
    /**
     * The question text
     */
    question: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Points for this question
     */
    points?: number | null;
    /**
     * Answer options (for multiple choice/select)
     */
    options?:
      | {
          text: string;
          /**
           * ⚠️ SENSITIVE: Marks this as the correct answer
           */
          isCorrect?: boolean | null;
          /**
           * Feedback shown when this option is selected
           */
          feedback?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * ⚠️ SENSITIVE: The correct answer (True or False)
     */
    correctAnswer?: boolean | null;
    /**
     * ⚠️ SENSITIVE: Accepted answers (case-insensitive matching)
     */
    acceptedAnswers?:
      | {
          answer: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Essay question settings
     */
    essaySettings?: {
      /**
       * Minimum word count
       */
      minWords?: number | null;
      /**
       * Maximum word count
       */
      maxWords?: number | null;
      /**
       * Grading rubric for instructors
       */
      rubric?: string | null;
    };
    /**
     * Explanation shown after answering (for learning)
     */
    explanation?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  /**
   * Whether this quiz is available to learners
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Student enrollments in courses
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  /**
   * The subscriber enrolled in the course
   */
  subscriber: number | SubscriberProfile;
  /**
   * The course the subscriber is enrolled in
   */
  course: number | Course;
  status: 'active' | 'completed' | 'paused' | 'expired' | 'cancelled';
  /**
   * Date and time of enrollment
   */
  enrolledAt: string;
  /**
   * When the learner first accessed the course
   */
  startedAt?: string | null;
  /**
   * When the learner completed the course
   */
  completedAt?: string | null;
  /**
   * When enrollment access expires (if applicable)
   */
  expiresAt?: string | null;
  /**
   * Overall course progress
   */
  progress?: {
    /**
     * Overall completion percentage
     */
    percentComplete?: number | null;
    lessonsCompleted?: number | null;
    totalLessons?: number | null;
    modulesCompleted?: number | null;
    totalModules?: number | null;
    /**
     * Last time the learner accessed the course
     */
    lastAccessedAt?: string | null;
    /**
     * Total time spent in minutes
     */
    timeSpent?: number | null;
  };
  /**
   * Completion certificate details
   */
  certificate?: {
    issued?: boolean | null;
    issuedAt?: string | null;
    /**
     * Unique certificate identifier
     */
    certificateId?: string | null;
    /**
     * URL to view/download certificate
     */
    certificateUrl?: string | null;
  };
  /**
   * Admin notes about this enrollment
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual lesson and quiz progress tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress".
 */
export interface Progress {
  id: number;
  /**
   * The enrollment this progress belongs to
   */
  enrollment: number | Enrollment;
  /**
   * The lesson being tracked
   */
  lesson: number | Lesson;
  status: 'not-started' | 'in-progress' | 'completed' | 'skipped';
  /**
   * When the learner first accessed this lesson
   */
  startedAt?: string | null;
  /**
   * When the learner completed this lesson
   */
  completedAt?: string | null;
  /**
   * Last time the learner accessed this lesson
   */
  lastAccessedAt?: string | null;
  /**
   * Video-specific progress tracking
   */
  videoProgress?: {
    /**
     * Seconds of video watched
     */
    watchedSeconds?: number | null;
    /**
     * Total video duration in seconds
     */
    totalSeconds?: number | null;
    percentWatched?: number | null;
    /**
     * Last playback position to resume from
     */
    lastPosition?: number | null;
  };
  /**
   * Total time spent on this lesson (in seconds)
   */
  timeSpent?: number | null;
  /**
   * Learner notes for this lesson
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Video/content bookmarks
   */
  bookmarks?:
    | {
        /**
         * Position in seconds (for video/audio)
         */
        timestamp?: number | null;
        note?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quiz attempt records and answers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts".
 */
export interface QuizAttempt {
  id: number;
  /**
   * The enrollment this attempt belongs to
   */
  enrollment: number | Enrollment;
  /**
   * The quiz being attempted
   */
  quiz: number | Quiz;
  /**
   * Which attempt this is (1st, 2nd, etc.)
   */
  attemptNumber: number;
  status: 'in-progress' | 'submitted' | 'graded' | 'expired';
  startedAt: string;
  submittedAt?: string | null;
  gradedAt?: string | null;
  /**
   * Time spent in seconds
   */
  timeSpent?: number | null;
  /**
   * Submitted answers for each question
   */
  answers?:
    | {
        /**
         * Index of the question in the quiz
         */
        questionIndex: number;
        /**
         * Type of question for reference
         */
        questionType?: string | null;
        /**
         * Selected option indices
         */
        selectedOptions?:
          | {
              optionIndex?: number | null;
              id?: string | null;
            }[]
          | null;
        textAnswer?: string | null;
        essayAnswer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Whether the answer is correct
         */
        isCorrect?: boolean | null;
        /**
         * Points awarded for this answer
         */
        pointsAwarded?: number | null;
        /**
         * Instructor feedback for this answer
         */
        feedback?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Quiz score
   */
  score?: {
    pointsEarned?: number | null;
    pointsPossible?: number | null;
    percentage?: number | null;
  };
  /**
   * Whether the learner passed the quiz
   */
  passed?: boolean | null;
  /**
   * Overall feedback from the instructor
   */
  instructorFeedback?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Instructor who graded this attempt (for essay questions)
   */
  gradedBy?: (number | null) | CoachProfile;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: number;
  email: string;
  /**
   * Whether this subscriber is actively receiving emails
   */
  active?: boolean | null;
  /**
   * Resend Contact ID for sync tracking
   */
  resendContactId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 1:1 coaching session bookings with coaches
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-sessions".
 */
export interface CoachingSession {
  id: number;
  /**
   * Title for this coaching session / type of session
   */
  sessionTitle: string;
  /**
   * The coach for this 1:1 session
   */
  coach: number | CoachProfile;
  /**
   * Name of the person booking the session
   */
  bookerName: string;
  /**
   * Email for booking confirmations and reminders
   */
  bookerEmail: string;
  /**
   * Optional phone number for contact
   */
  bookerPhone?: string | null;
  /**
   * If booked by a registered user, linked here
   */
  bookedByUser?: (number | null) | User;
  /**
   * Date and time of the scheduled session
   */
  scheduledAt: string;
  /**
   * Session duration in minutes (Max 30)
   */
  duration: number;
  /**
   * Timezone of the booker
   */
  timezone?:
    | (
        | 'UTC'
        | 'Africa/Abidjan'
        | 'Africa/Accra'
        | 'Africa/Addis_Ababa'
        | 'Africa/Algiers'
        | 'Africa/Asmera'
        | 'Africa/Bamako'
        | 'Africa/Bangui'
        | 'Africa/Banjul'
        | 'Africa/Bissau'
        | 'Africa/Blantyre'
        | 'Africa/Brazzaville'
        | 'Africa/Bujumbura'
        | 'Africa/Cairo'
        | 'Africa/Casablanca'
        | 'Africa/Ceuta'
        | 'Africa/Conakry'
        | 'Africa/Dakar'
        | 'Africa/Dar_es_Salaam'
        | 'Africa/Djibouti'
        | 'Africa/Douala'
        | 'Africa/El_Aaiun'
        | 'Africa/Freetown'
        | 'Africa/Gaborone'
        | 'Africa/Harare'
        | 'Africa/Johannesburg'
        | 'Africa/Juba'
        | 'Africa/Kampala'
        | 'Africa/Khartoum'
        | 'Africa/Kigali'
        | 'Africa/Kinshasa'
        | 'Africa/Lagos'
        | 'Africa/Libreville'
        | 'Africa/Lome'
        | 'Africa/Luanda'
        | 'Africa/Lubumbashi'
        | 'Africa/Lusaka'
        | 'Africa/Malabo'
        | 'Africa/Maputo'
        | 'Africa/Maseru'
        | 'Africa/Mbabane'
        | 'Africa/Mogadishu'
        | 'Africa/Monrovia'
        | 'Africa/Nairobi'
        | 'Africa/Ndjamena'
        | 'Africa/Niamey'
        | 'Africa/Nouakchott'
        | 'Africa/Ouagadougou'
        | 'Africa/Porto-Novo'
        | 'Africa/Sao_Tome'
        | 'Africa/Tripoli'
        | 'Africa/Tunis'
        | 'Africa/Windhoek'
        | 'America/Adak'
        | 'America/Anchorage'
        | 'America/Anguilla'
        | 'America/Antigua'
        | 'America/Araguaina'
        | 'America/Argentina/La_Rioja'
        | 'America/Argentina/Rio_Gallegos'
        | 'America/Argentina/Salta'
        | 'America/Argentina/San_Juan'
        | 'America/Argentina/San_Luis'
        | 'America/Argentina/Tucuman'
        | 'America/Argentina/Ushuaia'
        | 'America/Aruba'
        | 'America/Asuncion'
        | 'America/Bahia'
        | 'America/Bahia_Banderas'
        | 'America/Barbados'
        | 'America/Belem'
        | 'America/Belize'
        | 'America/Blanc-Sablon'
        | 'America/Boa_Vista'
        | 'America/Bogota'
        | 'America/Boise'
        | 'America/Buenos_Aires'
        | 'America/Cambridge_Bay'
        | 'America/Campo_Grande'
        | 'America/Cancun'
        | 'America/Caracas'
        | 'America/Catamarca'
        | 'America/Cayenne'
        | 'America/Cayman'
        | 'America/Chicago'
        | 'America/Chihuahua'
        | 'America/Ciudad_Juarez'
        | 'America/Coral_Harbour'
        | 'America/Cordoba'
        | 'America/Costa_Rica'
        | 'America/Coyhaique'
        | 'America/Creston'
        | 'America/Cuiaba'
        | 'America/Curacao'
        | 'America/Danmarkshavn'
        | 'America/Dawson'
        | 'America/Dawson_Creek'
        | 'America/Denver'
        | 'America/Detroit'
        | 'America/Dominica'
        | 'America/Edmonton'
        | 'America/Eirunepe'
        | 'America/El_Salvador'
        | 'America/Fort_Nelson'
        | 'America/Fortaleza'
        | 'America/Glace_Bay'
        | 'America/Godthab'
        | 'America/Goose_Bay'
        | 'America/Grand_Turk'
        | 'America/Grenada'
        | 'America/Guadeloupe'
        | 'America/Guatemala'
        | 'America/Guayaquil'
        | 'America/Guyana'
        | 'America/Halifax'
        | 'America/Havana'
        | 'America/Hermosillo'
        | 'America/Indiana/Knox'
        | 'America/Indiana/Marengo'
        | 'America/Indiana/Petersburg'
        | 'America/Indiana/Tell_City'
        | 'America/Indiana/Vevay'
        | 'America/Indiana/Vincennes'
        | 'America/Indiana/Winamac'
        | 'America/Indianapolis'
        | 'America/Inuvik'
        | 'America/Iqaluit'
        | 'America/Jamaica'
        | 'America/Jujuy'
        | 'America/Juneau'
        | 'America/Kentucky/Monticello'
        | 'America/Kralendijk'
        | 'America/La_Paz'
        | 'America/Lima'
        | 'America/Los_Angeles'
        | 'America/Louisville'
        | 'America/Lower_Princes'
        | 'America/Maceio'
        | 'America/Managua'
        | 'America/Manaus'
        | 'America/Marigot'
        | 'America/Martinique'
        | 'America/Matamoros'
        | 'America/Mazatlan'
        | 'America/Mendoza'
        | 'America/Menominee'
        | 'America/Merida'
        | 'America/Metlakatla'
        | 'America/Mexico_City'
        | 'America/Miquelon'
        | 'America/Moncton'
        | 'America/Monterrey'
        | 'America/Montevideo'
        | 'America/Montserrat'
        | 'America/Nassau'
        | 'America/New_York'
        | 'America/Nome'
        | 'America/Noronha'
        | 'America/North_Dakota/Beulah'
        | 'America/North_Dakota/Center'
        | 'America/North_Dakota/New_Salem'
        | 'America/Ojinaga'
        | 'America/Panama'
        | 'America/Paramaribo'
        | 'America/Phoenix'
        | 'America/Port-au-Prince'
        | 'America/Port_of_Spain'
        | 'America/Porto_Velho'
        | 'America/Puerto_Rico'
        | 'America/Punta_Arenas'
        | 'America/Rankin_Inlet'
        | 'America/Recife'
        | 'America/Regina'
        | 'America/Resolute'
        | 'America/Rio_Branco'
        | 'America/Santarem'
        | 'America/Santiago'
        | 'America/Santo_Domingo'
        | 'America/Sao_Paulo'
        | 'America/Scoresbysund'
        | 'America/Sitka'
        | 'America/St_Barthelemy'
        | 'America/St_Johns'
        | 'America/St_Kitts'
        | 'America/St_Lucia'
        | 'America/St_Thomas'
        | 'America/St_Vincent'
        | 'America/Swift_Current'
        | 'America/Tegucigalpa'
        | 'America/Thule'
        | 'America/Tijuana'
        | 'America/Toronto'
        | 'America/Tortola'
        | 'America/Vancouver'
        | 'America/Whitehorse'
        | 'America/Winnipeg'
        | 'America/Yakutat'
        | 'Antarctica/Casey'
        | 'Antarctica/Davis'
        | 'Antarctica/DumontDUrville'
        | 'Antarctica/Macquarie'
        | 'Antarctica/Mawson'
        | 'Antarctica/McMurdo'
        | 'Antarctica/Palmer'
        | 'Antarctica/Rothera'
        | 'Antarctica/Syowa'
        | 'Antarctica/Troll'
        | 'Antarctica/Vostok'
        | 'Arctic/Longyearbyen'
        | 'Asia/Aden'
        | 'Asia/Almaty'
        | 'Asia/Amman'
        | 'Asia/Anadyr'
        | 'Asia/Aqtau'
        | 'Asia/Aqtobe'
        | 'Asia/Ashgabat'
        | 'Asia/Atyrau'
        | 'Asia/Baghdad'
        | 'Asia/Bahrain'
        | 'Asia/Baku'
        | 'Asia/Bangkok'
        | 'Asia/Barnaul'
        | 'Asia/Beirut'
        | 'Asia/Bishkek'
        | 'Asia/Brunei'
        | 'Asia/Calcutta'
        | 'Asia/Chita'
        | 'Asia/Colombo'
        | 'Asia/Damascus'
        | 'Asia/Dhaka'
        | 'Asia/Dili'
        | 'Asia/Dubai'
        | 'Asia/Dushanbe'
        | 'Asia/Famagusta'
        | 'Asia/Gaza'
        | 'Asia/Hebron'
        | 'Asia/Hong_Kong'
        | 'Asia/Hovd'
        | 'Asia/Irkutsk'
        | 'Asia/Jakarta'
        | 'Asia/Jayapura'
        | 'Asia/Jerusalem'
        | 'Asia/Kabul'
        | 'Asia/Kamchatka'
        | 'Asia/Karachi'
        | 'Asia/Katmandu'
        | 'Asia/Khandyga'
        | 'Asia/Krasnoyarsk'
        | 'Asia/Kuala_Lumpur'
        | 'Asia/Kuching'
        | 'Asia/Kuwait'
        | 'Asia/Macau'
        | 'Asia/Magadan'
        | 'Asia/Makassar'
        | 'Asia/Manila'
        | 'Asia/Muscat'
        | 'Asia/Nicosia'
        | 'Asia/Novokuznetsk'
        | 'Asia/Novosibirsk'
        | 'Asia/Omsk'
        | 'Asia/Oral'
        | 'Asia/Phnom_Penh'
        | 'Asia/Pontianak'
        | 'Asia/Pyongyang'
        | 'Asia/Qatar'
        | 'Asia/Qostanay'
        | 'Asia/Qyzylorda'
        | 'Asia/Rangoon'
        | 'Asia/Riyadh'
        | 'Asia/Saigon'
        | 'Asia/Sakhalin'
        | 'Asia/Samarkand'
        | 'Asia/Seoul'
        | 'Asia/Shanghai'
        | 'Asia/Singapore'
        | 'Asia/Srednekolymsk'
        | 'Asia/Taipei'
        | 'Asia/Tashkent'
        | 'Asia/Tbilisi'
        | 'Asia/Tehran'
        | 'Asia/Thimphu'
        | 'Asia/Tokyo'
        | 'Asia/Tomsk'
        | 'Asia/Ulaanbaatar'
        | 'Asia/Urumqi'
        | 'Asia/Ust-Nera'
        | 'Asia/Vientiane'
        | 'Asia/Vladivostok'
        | 'Asia/Yakutsk'
        | 'Asia/Yekaterinburg'
        | 'Asia/Yerevan'
        | 'Atlantic/Azores'
        | 'Atlantic/Bermuda'
        | 'Atlantic/Canary'
        | 'Atlantic/Cape_Verde'
        | 'Atlantic/Faeroe'
        | 'Atlantic/Madeira'
        | 'Atlantic/Reykjavik'
        | 'Atlantic/South_Georgia'
        | 'Atlantic/St_Helena'
        | 'Atlantic/Stanley'
        | 'Australia/Adelaide'
        | 'Australia/Brisbane'
        | 'Australia/Broken_Hill'
        | 'Australia/Darwin'
        | 'Australia/Eucla'
        | 'Australia/Hobart'
        | 'Australia/Lindeman'
        | 'Australia/Lord_Howe'
        | 'Australia/Melbourne'
        | 'Australia/Perth'
        | 'Australia/Sydney'
        | 'Europe/Amsterdam'
        | 'Europe/Andorra'
        | 'Europe/Astrakhan'
        | 'Europe/Athens'
        | 'Europe/Belgrade'
        | 'Europe/Berlin'
        | 'Europe/Bratislava'
        | 'Europe/Brussels'
        | 'Europe/Bucharest'
        | 'Europe/Budapest'
        | 'Europe/Busingen'
        | 'Europe/Chisinau'
        | 'Europe/Copenhagen'
        | 'Europe/Dublin'
        | 'Europe/Gibraltar'
        | 'Europe/Guernsey'
        | 'Europe/Helsinki'
        | 'Europe/Isle_of_Man'
        | 'Europe/Istanbul'
        | 'Europe/Jersey'
        | 'Europe/Kaliningrad'
        | 'Europe/Kiev'
        | 'Europe/Kirov'
        | 'Europe/Lisbon'
        | 'Europe/Ljubljana'
        | 'Europe/London'
        | 'Europe/Luxembourg'
        | 'Europe/Madrid'
        | 'Europe/Malta'
        | 'Europe/Mariehamn'
        | 'Europe/Minsk'
        | 'Europe/Monaco'
        | 'Europe/Moscow'
        | 'Europe/Oslo'
        | 'Europe/Paris'
        | 'Europe/Podgorica'
        | 'Europe/Prague'
        | 'Europe/Riga'
        | 'Europe/Rome'
        | 'Europe/Samara'
        | 'Europe/San_Marino'
        | 'Europe/Sarajevo'
        | 'Europe/Saratov'
        | 'Europe/Simferopol'
        | 'Europe/Skopje'
        | 'Europe/Sofia'
        | 'Europe/Stockholm'
        | 'Europe/Tallinn'
        | 'Europe/Tirane'
        | 'Europe/Ulyanovsk'
        | 'Europe/Vaduz'
        | 'Europe/Vatican'
        | 'Europe/Vienna'
        | 'Europe/Vilnius'
        | 'Europe/Volgograd'
        | 'Europe/Warsaw'
        | 'Europe/Zagreb'
        | 'Europe/Zurich'
        | 'Indian/Antananarivo'
        | 'Indian/Chagos'
        | 'Indian/Christmas'
        | 'Indian/Cocos'
        | 'Indian/Comoro'
        | 'Indian/Kerguelen'
        | 'Indian/Mahe'
        | 'Indian/Maldives'
        | 'Indian/Mauritius'
        | 'Indian/Mayotte'
        | 'Indian/Reunion'
        | 'Pacific/Apia'
        | 'Pacific/Auckland'
        | 'Pacific/Bougainville'
        | 'Pacific/Chatham'
        | 'Pacific/Easter'
        | 'Pacific/Efate'
        | 'Pacific/Enderbury'
        | 'Pacific/Fakaofo'
        | 'Pacific/Fiji'
        | 'Pacific/Funafuti'
        | 'Pacific/Galapagos'
        | 'Pacific/Gambier'
        | 'Pacific/Guadalcanal'
        | 'Pacific/Guam'
        | 'Pacific/Honolulu'
        | 'Pacific/Kiritimati'
        | 'Pacific/Kosrae'
        | 'Pacific/Kwajalein'
        | 'Pacific/Majuro'
        | 'Pacific/Marquesas'
        | 'Pacific/Midway'
        | 'Pacific/Nauru'
        | 'Pacific/Niue'
        | 'Pacific/Norfolk'
        | 'Pacific/Noumea'
        | 'Pacific/Pago_Pago'
        | 'Pacific/Palau'
        | 'Pacific/Pitcairn'
        | 'Pacific/Ponape'
        | 'Pacific/Port_Moresby'
        | 'Pacific/Rarotonga'
        | 'Pacific/Saipan'
        | 'Pacific/Tahiti'
        | 'Pacific/Tarawa'
        | 'Pacific/Tongatapu'
        | 'Pacific/Truk'
        | 'Pacific/Wake'
        | 'Pacific/Wallis'
      )
    | null;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no-show' | 'rescheduled';
  /**
   * How the session will be conducted
   */
  sessionType?: ('video' | 'phone' | 'in-person') | null;
  /**
   * Video call link - Auto-generated using Zoom API
   */
  meetingLink?: string | null;
  /**
   * Zoom details (System managed)
   */
  zoomMeeting?: {
    /**
     * Zoom Join URL
     */
    joinUrl?: string | null;
    /**
     * Meeting ID
     */
    meetingId?: string | null;
    password?: string | null;
    createdAt?: string | null;
  };
  /**
   * What the booker wants to discuss
   */
  topic?: string | null;
  /**
   * Additional notes from the booker
   */
  bookerNotes?: string | null;
  /**
   * Private notes from the coach
   */
  coachNotes?: string | null;
  /**
   * When the booking was created
   */
  bookedAt?: string | null;
  /**
   * When the session was confirmed
   */
  confirmedAt?: string | null;
  /**
   * When the session was cancelled (if applicable)
   */
  cancelledAt?: string | null;
  /**
   * Reason for cancellation
   */
  cancellationReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'coach-profiles';
        value: number | CoachProfile;
      } | null)
    | ({
        relationTo: 'subscriber-profiles';
        value: number | SubscriberProfile;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'modules';
        value: number | Module;
      } | null)
    | ({
        relationTo: 'lessons';
        value: number | Lesson;
      } | null)
    | ({
        relationTo: 'quizzes';
        value: number | Quiz;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'progress';
        value: number | Progress;
      } | null)
    | ({
        relationTo: 'quiz-attempts';
        value: number | QuizAttempt;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: number | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'coaching-sessions';
        value: number | CoachingSession;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  isActive?: T;
  resendContactId?: T;
  isFirstLogin?: T;
  unsubscribed?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  isSubscriberOnly?: T;
  category?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coach-profiles_select".
 */
export interface CoachProfilesSelect<T extends boolean = true> {
  user?: T;
  displayName?: T;
  slug?: T;
  bio?: T;
  profilePhoto?: T;
  expertise?:
    | T
    | {
        area?: T;
        id?: T;
      };
  experience?:
    | T
    | {
        yearsOfExperience?: T;
        credentials?: T;
        previousWork?: T;
      };
  isActive?: T;
  socialLinks?:
    | T
    | {
        website?: T;
        linkedin?: T;
        twitter?: T;
      };
  timezone?: T;
  availability?:
    | T
    | {
        day?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriber-profiles_select".
 */
export interface SubscriberProfilesSelect<T extends boolean = true> {
  user?: T;
  displayName?: T;
  avatar?: T;
  isAnonymous?: T;
  interests?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  metadata?:
    | T
    | {
        timezone?: T;
        language?: T;
        joinedAt?: T;
      };
  learningPreferences?:
    | T
    | {
        preferredFormat?: T;
        pace?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  tags?: T;
  isSubscriberOnly?: T;
  publishedAt?: T;
  isPublished?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  content?: T;
  isPublished?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  shortDescription?: T;
  instructor?: T;
  additionalInstructors?: T;
  thumbnail?: T;
  coverImage?: T;
  previewVideo?: T;
  modules?: T;
  difficulty?: T;
  duration?:
    | T
    | {
        hours?: T;
        minutes?: T;
      };
  topics?:
    | T
    | {
        topic?: T;
        id?: T;
      };
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  prerequisites?:
    | T
    | {
        prerequisite?: T;
        id?: T;
      };
  enrollment?:
    | T
    | {
        isOpen?: T;
        maxEnrollments?: T;
        startDate?: T;
        endDate?: T;
      };
  isPublished?: T;
  publishedAt?: T;
  category?: T;
  tags?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "modules_select".
 */
export interface ModulesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  lessons?: T;
  completionRequirements?:
    | T
    | {
        requireAllLessons?: T;
        minimumLessons?: T;
        requireQuizPass?: T;
      };
  estimatedDuration?:
    | T
    | {
        hours?: T;
        minutes?: T;
      };
  objectives?:
    | T
    | {
        objective?: T;
        id?: T;
      };
  quiz?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lessons_select".
 */
export interface LessonsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  order?: T;
  type?: T;
  videoContent?:
    | T
    | {
        videoUrl?: T;
        videoFile?: T;
        transcript?: T;
        captions?: T;
      };
  textContent?: T;
  audioContent?:
    | T
    | {
        audioFile?: T;
        transcript?: T;
      };
  quiz?: T;
  resources?:
    | T
    | {
        title?: T;
        file?: T;
        description?: T;
        id?: T;
      };
  duration?:
    | T
    | {
        hours?: T;
        minutes?: T;
      };
  isFree?: T;
  completionCriteria?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quizzes_select".
 */
export interface QuizzesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  settings?:
    | T
    | {
        timeLimit?: T;
        passingScore?: T;
        maxAttempts?: T;
        shuffleQuestions?: T;
        showCorrectAnswers?: T;
        allowReview?: T;
      };
  questions?:
    | T
    | {
        questionType?: T;
        question?: T;
        points?: T;
        options?:
          | T
          | {
              text?: T;
              isCorrect?: T;
              feedback?: T;
              id?: T;
            };
        correctAnswer?: T;
        acceptedAnswers?:
          | T
          | {
              answer?: T;
              id?: T;
            };
        essaySettings?:
          | T
          | {
              minWords?: T;
              maxWords?: T;
              rubric?: T;
            };
        explanation?: T;
        id?: T;
      };
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  subscriber?: T;
  course?: T;
  status?: T;
  enrolledAt?: T;
  startedAt?: T;
  completedAt?: T;
  expiresAt?: T;
  progress?:
    | T
    | {
        percentComplete?: T;
        lessonsCompleted?: T;
        totalLessons?: T;
        modulesCompleted?: T;
        totalModules?: T;
        lastAccessedAt?: T;
        timeSpent?: T;
      };
  certificate?:
    | T
    | {
        issued?: T;
        issuedAt?: T;
        certificateId?: T;
        certificateUrl?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "progress_select".
 */
export interface ProgressSelect<T extends boolean = true> {
  enrollment?: T;
  lesson?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  lastAccessedAt?: T;
  videoProgress?:
    | T
    | {
        watchedSeconds?: T;
        totalSeconds?: T;
        percentWatched?: T;
        lastPosition?: T;
      };
  timeSpent?: T;
  notes?: T;
  bookmarks?:
    | T
    | {
        timestamp?: T;
        note?: T;
        createdAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-attempts_select".
 */
export interface QuizAttemptsSelect<T extends boolean = true> {
  enrollment?: T;
  quiz?: T;
  attemptNumber?: T;
  status?: T;
  startedAt?: T;
  submittedAt?: T;
  gradedAt?: T;
  timeSpent?: T;
  answers?:
    | T
    | {
        questionIndex?: T;
        questionType?: T;
        selectedOptions?:
          | T
          | {
              optionIndex?: T;
              id?: T;
            };
        textAnswer?: T;
        essayAnswer?: T;
        isCorrect?: T;
        pointsAwarded?: T;
        feedback?: T;
        id?: T;
      };
  score?:
    | T
    | {
        pointsEarned?: T;
        pointsPossible?: T;
        percentage?: T;
      };
  passed?: T;
  instructorFeedback?: T;
  gradedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  active?: T;
  resendContactId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaching-sessions_select".
 */
export interface CoachingSessionsSelect<T extends boolean = true> {
  sessionTitle?: T;
  coach?: T;
  bookerName?: T;
  bookerEmail?: T;
  bookerPhone?: T;
  bookedByUser?: T;
  scheduledAt?: T;
  duration?: T;
  timezone?: T;
  status?: T;
  sessionType?: T;
  meetingLink?: T;
  zoomMeeting?:
    | T
    | {
        joinUrl?: T;
        meetingId?: T;
        password?: T;
        createdAt?: T;
      };
  topic?: T;
  bookerNotes?: T;
  coachNotes?: T;
  bookedAt?: T;
  confirmedAt?: T;
  cancelledAt?: T;
  cancellationReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    badge: string;
    title: string;
    highlightedText: string;
    description: string;
    primaryButtonText: string;
    primaryButtonLink: string;
    secondaryButtonText: string;
    secondaryButtonLink: string;
  };
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  featuresHeader: {
    badge: string;
    title: string;
    description: string;
  };
  features?:
    | {
        icon: 'BookOpen' | 'Users' | 'Sparkles' | 'GraduationCap';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  testimonialsHeader: {
    badge: string;
    title: string;
  };
  reviews?:
    | {
        name: string;
        role: string;
        content: string;
        avatar: string;
        id?: string | null;
      }[]
    | null;
  cta: {
    title: string;
    description: string;
    buttonText: string;
    buttonLink: string;
    benefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Blog listing page hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  hero: {
    /**
     * Badge text displayed above the title
     */
    badge: string;
    /**
     * Main heading for the blog page
     */
    title: string;
    /**
     * Subtitle/description text
     */
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Courses listing page hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page".
 */
export interface CoursesPage {
  id: number;
  hero: {
    /**
     * Badge text displayed above the title
     */
    badge: string;
    /**
     * Main heading for the courses page
     */
    title: string;
    /**
     * Subtitle/description text
     */
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the Coaches listing page hero section
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches-page".
 */
export interface CoachesPage {
  id: number;
  hero: {
    /**
     * Badge text displayed above the title
     */
    badge: string;
    /**
     * Main heading for the coaches page
     */
    title: string;
    /**
     * Subtitle/description text
     */
    description: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the header navigation menu
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: number;
  navigationLinks: {
    name: string;
    href: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Manage the footer content and links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content".
 */
export interface FooterContent {
  id: number;
  /**
   * Short description displayed under the logo
   */
  description: string;
  companyLinks: {
    name: string;
    href: string;
    id?: string | null;
  }[];
  legalLinks: {
    name: string;
    href: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meilisearch-admin".
 */
export interface MeilisearchAdmin {
  id: number;
  lastReindex?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  maintenanceMode?: {
    isEnabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    expectedLaunchDate?: string | null;
    showNewsletter?: boolean | null;
  };
  socialLinks?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    threads?: string | null;
    github?: string | null;
    discord?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        highlightedText?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  featuresHeader?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  testimonialsHeader?:
    | T
    | {
        badge?: T;
        title?: T;
      };
  reviews?:
    | T
    | {
        name?: T;
        role?: T;
        content?: T;
        avatar?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses-page_select".
 */
export interface CoursesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coaches-page_select".
 */
export interface CoachesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  navigationLinks?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-content_select".
 */
export interface FooterContentSelect<T extends boolean = true> {
  description?: T;
  companyLinks?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        name?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "meilisearch-admin_select".
 */
export interface MeilisearchAdminSelect<T extends boolean = true> {
  lastReindex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  maintenanceMode?:
    | T
    | {
        isEnabled?: T;
        title?: T;
        description?: T;
        expectedLaunchDate?: T;
        showNewsletter?: T;
      };
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        youtube?: T;
        tiktok?: T;
        threads?: T;
        github?: T;
        discord?: T;
        whatsapp?: T;
        telegram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}